const keys = {
  en: {
    Backquote: {
      key: '§',
      valueNormal: '§',
      valueShift: '±',
      valueCaps: '§',
      modifier: false,
    },
    Digit1: {
      key: '1',
      valueNormal: '1',
      valueShift: '!',
      valueCaps: '1',
      modifier: false,
    },
    Digit2: {
      key: '2',
      valueNormal: '2',
      valueShift: '@',
      valueCaps: '2',
      modifier: false,
    },
    Digit3: {
      key: '3',
      valueNormal: '3',
      valueShift: '#',
      valueCaps: '3',
      modifier: false,
    },
    Digit4: {
      key: '4',
      valueNormal: '4',
      valueShift: '$',
      valueCaps: '4',
      modifier: false,
    },
    Digit5: {
      key: '5',
      valueNormal: '5',
      valueShift: '%',
      valueCaps: '5',
      modifier: false,
    },
    Digit6: {
      key: '6',
      valueNormal: '6',
      valueShift: '^',
      valueCaps: '6',
      modifier: false,
    },
    Digit7: {
      key: '7',
      valueNormal: '7',
      valueShift: '&',
      valueCaps: '7',
      modifier: false,
    },
    Digit8: {
      key: '8',
      valueNormal: '8',
      valueShift: '*',
      valueCaps: '8',
      modifier: false,
    },
    Digit9: {
      key: '9',
      valueNormal: '9',
      valueShift: '(',
      valueCaps: '9',
      modifier: false,
    },
    Digit0: {
      key: '0',
      valueNormal: '0',
      valueShift: ')',
      valueCaps: '0',
      modifier: false,
    },
    Minus: {
      key: '-',
      valueNormal: '-',
      valueShift: '_',
      valueCaps: '-',
      modifier: false,
    },
    Equal: {
      key: '=',
      valueNormal: '=',
      valueShift: '+',
      valueCaps: '=',
      modifier: false,
    },
    Backspace: {
      key: '←',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    Tab: {
      key: 'tab',
      valueNormal: '  ',
      valueShift: ' ',
      valueCaps: '',
      modifier: true,
    },
    KeyQ: {
      key: 'q',
      valueNormal: 'q',
      valueShift: 'Q',
      valueCaps: 'Q',
      modifier: false,
    },
    KeyW: {
      key: 'w',
      valueNormal: 'w',
      valueShift: 'W',
      valueCaps: 'W',
      modifier: false,
    },
    KeyE: {
      key: 'e',
      valueNormal: 'e',
      valueShift: 'E',
      valueCaps: 'E',
      modifier: false,
    },
    KeyR: {
      key: 'r',
      valueNormal: 'r',
      valueShift: 'R',
      valueCaps: 'R',
      modifier: false,
    },
    KeyT: {
      key: 't',
      valueNormal: 't',
      valueShift: 'T',
      valueCaps: 'T',
      modifier: false,
    },
    KeyY: {
      key: 'y',
      valueNormal: 'y',
      valueShift: 'Y',
      valueCaps: 'Y',
      modifier: false,
    },
    KeyU: {
      key: 'u',
      valueNormal: 'u',
      valueShift: 'U',
      valueCaps: 'U',
      modifier: false,
    },
    KeyI: {
      key: 'i',
      valueNormal: 'i',
      valueShift: 'I',
      valueCaps: 'I',
      modifier: false,
    },
    KeyO: {
      key: 'o',
      valueNormal: 'o',
      valueShift: 'O',
      valueCaps: 'O',
      modifier: false,
    },
    KeyP: {
      key: 'p',
      valueNormal: 'p',
      valueShift: 'P',
      valueCaps: 'P',
      modifier: false,
    },
    BracketLeft: {
      key: '[',
      valueNormal: '[',
      valueShift: '{',
      valueCaps: '[',
      modifier: false,
    },
    BracketRight: {
      key: ']',
      valueNormal: ']',
      valueShift: '}',
      valueCaps: ']',
      modifier: false,
    },
    Enter: {
      key: 'Enter',
      valueNormal: '\n',
      valueShift: '\n',
      valueCaps: '\n',
      modifier: false,
    },
    CapsLock: {
      key: 'capsLock',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    KeyA: {
      key: 'a',
      valueNormal: 'a',
      valueShift: 'A',
      valueCaps: 'A',
      modifier: false,
    },
    KeyS: {
      key: 's',
      valueNormal: 's',
      valueShift: 'S',
      valueCaps: 'S',
      modifier: false,
    },
    KeyD: {
      key: 'd',
      valueNormal: 'd',
      valueShift: 'D',
      valueCaps: 'D',
      modifier: false,
    },
    KeyF: {
      key: 'f',
      valueNormal: 'f',
      valueShift: 'F',
      valueCaps: 'F',
      modifier: false,
    },
    KeyG: {
      key: 'g',
      valueNormal: 'g',
      valueShift: 'G',
      valueCaps: 'G',
      modifier: false,
    },
    KeyH: {
      key: 'h',
      valueNormal: 'h',
      valueShift: 'H',
      valueCaps: 'H',
      modifier: false,
    },
    KeyJ: {
      key: 'j',
      valueNormal: 'j',
      valueShift: 'J',
      valueCaps: 'J',
      modifier: false,
    },
    KeyK: {
      key: 'k',
      valueNormal: 'k',
      valueShift: 'K',
      valueCaps: 'K',
      modifier: false,
    },
    KeyL: {
      key: 'l',
      valueNormal: 'l',
      valueShift: 'L',
      valueCaps: 'L',
      modifier: false,
    },
    Semicolon: {
      key: ';',
      valueNormal: ';',
      valueShift: ':',
      valueCaps: ';',
      modifier: false,
    },
    Quote: {
      key: '\'',
      valueNormal: '\'',
      valueShift: '"',
      valueCaps: '\'',
      modifier: false,
    },
    Backslash: {
      key: '\\',
      valueNormal: '\\',
      valueShift: '|',
      valueCaps: '\\',
      modifier: false,
    },
    ShiftLeft: {
      key: 'shift',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    IntlBackslash: {
      key: '`',
      valueNormal: '`',
      valueShift: '~',
      valueCaps: '`',
      modifier: false,
    },
    KeyZ: {
      key: 'z',
      valueNormal: 'z',
      valueShift: 'Z',
      valueCaps: 'Z',
      modifier: false,
    },
    KeyX: {
      key: 'x',
      valueNormal: 'x',
      valueShift: 'X',
      valueCaps: 'X',
      modifier: false,
    },
    KeyC: {
      key: 'c',
      valueNormal: 'c',
      valueShift: 'C',
      valueCaps: 'C',
      modifier: false,
    },
    KeyV: {
      key: 'v',
      valueNormal: 'v',
      valueShift: 'V',
      valueCaps: 'V',
      modifier: false,
    },
    KeyB: {
      key: 'b',
      valueNormal: 'b',
      valueShift: 'B',
      valueCaps: 'B',
      modifier: false,
    },
    KeyN: {
      key: 'n',
      valueNormal: 'n',
      valueShift: 'N',
      valueCaps: 'N',
      modifier: false,
    },
    KeyM: {
      key: 'm',
      valueNormal: 'm',
      valueShift: 'M',
      valueCaps: 'M',
      modifier: false,
    },
    Comma: {
      key: ',',
      valueNormal: ',',
      valueShift: '<',
      valueCaps: ',',
      modifier: false,
    },
    Period: {
      key: '.',
      valueNormal: '.',
      valueShift: '>',
      valueCaps: '.',
      modifier: false,
    },
    Slash: {
      key: '/',
      valueNormal: '/',
      valueShift: '?',
      valueCaps: '/',
      modifier: false,
    },
    ShiftRight: {
      key: 'shift',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    ControlLeft: {
      key: 'ctrl',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    AltLeft: {
      key: 'alt',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    MetaLeft: {
      key: 'cmd',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    Space: {
      key: ' ',
      valueNormal: ' ',
      valueShift: ' ',
      valueCaps: ' ',
      modifier: false,
    },
    MetaRight: {
      key: 'cmd',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    AltRight: {
      key: 'alt',
      valueNormal: '',
      valueShift: '',
      valueCaps: '',
      modifier: true,
    },
    ArrowLeft: {
      key: '<',
      valueNormal: '<',
      valueShift: '<',
      valueCaps: '<',
      modifier: false,
    },
    ArrowUp: {
      key: '^',
      valueNormal: '^',
      valueShift: '^',
      valueCaps: '^',
      modifier: false,
    },
    ArrowRight: {
      key: '>',
      valueNormal: '>',
      valueShift: '>',
      valueCaps: '>',
      modifier: false,
    },
    ArrowDown: {
      key: 'v',
      valueNormal: 'v',
      valueShift: 'v',
      valueCaps: 'v',
      modifier: false,
    },
  },
  ru: {},
};

export default keys;
