const keys = {
  en: {
    Backquote: {
      key: '§',
      valueNormal: '§',
      valueShift: '±',
      valueShiftCaps: '±',
      valueCaps: '§',
      modifier: false,
    },
    Digit1: {
      key: '1',
      valueNormal: '1',
      valueShift: '!',
      valueShiftCaps: '!',
      valueCaps: '1',
      modifier: false,
    },
    Digit2: {
      key: '2',
      valueNormal: '2',
      valueShift: '@',
      valueShiftCaps: '@',
      valueCaps: '2',
      modifier: false,
    },
    Digit3: {
      key: '3',
      valueNormal: '3',
      valueShift: '#',
      valueShiftCaps: '#',
      valueCaps: '3',
      modifier: false,
    },
    Digit4: {
      key: '4',
      valueNormal: '4',
      valueShift: '$',
      valueShiftCaps: '$',
      valueCaps: '4',
      modifier: false,
    },
    Digit5: {
      key: '5',
      valueNormal: '5',
      valueShift: '%',
      valueShiftCaps: '%',
      valueCaps: '5',
      modifier: false,
    },
    Digit6: {
      key: '6',
      valueNormal: '6',
      valueShift: '^',
      valueShiftCaps: '^',
      valueCaps: '6',
      modifier: false,
    },
    Digit7: {
      key: '7',
      valueNormal: '7',
      valueShift: '&',
      valueShiftCaps: '&',
      valueCaps: '7',
      modifier: false,
    },
    Digit8: {
      key: '8',
      valueNormal: '8',
      valueShift: '*',
      valueShiftCaps: '*',
      valueCaps: '8',
      modifier: false,
    },
    Digit9: {
      key: '9',
      valueNormal: '9',
      valueShift: '(',
      valueShiftCaps: '(',
      valueCaps: '9',
      modifier: false,
    },
    Digit0: {
      key: '0',
      valueNormal: '0',
      valueShift: ')',
      valueShiftCaps: ')',
      valueCaps: '0',
      modifier: false,
    },
    Minus: {
      key: '-',
      valueNormal: '-',
      valueShift: '_',
      valueShiftCaps: '_',
      valueCaps: '-',
      modifier: false,
    },
    Equal: {
      key: '=',
      valueNormal: '=',
      valueShift: '+',
      valueShiftCaps: '+',
      valueCaps: '=',
      modifier: false,
    },
    Backspace: {
      key: '←',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    Tab: {
      key: 'tab',
      valueNormal: '\t',
      valueShift: '\t',
      valueShiftCaps: '\t',
      valueCaps: '\t',
      modifier: false,
    },
    KeyQ: {
      key: 'q',
      valueNormal: 'q',
      valueShift: 'Q',
      valueShiftCaps: 'q',
      valueCaps: 'Q',
      modifier: false,
    },
    KeyW: {
      key: 'w',
      valueNormal: 'w',
      valueShift: 'W',
      valueShiftCaps: 'w',
      valueCaps: 'W',
      modifier: false,
    },
    KeyE: {
      key: 'e',
      valueNormal: 'e',
      valueShift: 'E',
      valueShiftCaps: 'e',
      valueCaps: 'E',
      modifier: false,
    },
    KeyR: {
      key: 'r',
      valueNormal: 'r',
      valueShift: 'R',
      valueShiftCaps: 'r',
      valueCaps: 'R',
      modifier: false,
    },
    KeyT: {
      key: 't',
      valueNormal: 't',
      valueShift: 'T',
      valueShiftCaps: 't',
      valueCaps: 'T',
      modifier: false,
    },
    KeyY: {
      key: 'y',
      valueNormal: 'y',
      valueShift: 'Y',
      valueShiftCaps: 'y',
      valueCaps: 'Y',
      modifier: false,
    },
    KeyU: {
      key: 'u',
      valueNormal: 'u',
      valueShift: 'U',
      valueShiftCaps: 'u',
      valueCaps: 'U',
      modifier: false,
    },
    KeyI: {
      key: 'i',
      valueNormal: 'i',
      valueShift: 'I',
      valueShiftCaps: 'i',
      valueCaps: 'I',
      modifier: false,
    },
    KeyO: {
      key: 'o',
      valueNormal: 'o',
      valueShift: 'O',
      valueShiftCaps: 'o',
      valueCaps: 'O',
      modifier: false,
    },
    KeyP: {
      key: 'p',
      valueNormal: 'p',
      valueShift: 'P',
      valueShiftCaps: 'p',
      valueCaps: 'P',
      modifier: false,
    },
    BracketLeft: {
      key: '[',
      valueNormal: '[',
      valueShift: '{',
      valueShiftCaps: '{',
      valueCaps: '[',
      modifier: false,
    },
    BracketRight: {
      key: ']',
      valueNormal: ']',
      valueShift: '}',
      valueShiftCaps: '}',
      valueCaps: ']',
      modifier: false,
    },
    Enter: {
      key: 'Enter',
      valueNormal: '\n',
      valueShift: '\n',
      valueShiftCaps: '\n',
      valueCaps: '\n',
      modifier: false,
    },
    CapsLock: {
      key: 'capsLock',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    KeyA: {
      key: 'a',
      valueNormal: 'a',
      valueShift: 'A',
      valueShiftCaps: 'a',
      valueCaps: 'A',
      modifier: false,
    },
    KeyS: {
      key: 's',
      valueNormal: 's',
      valueShift: 'S',
      valueShiftCaps: 's',
      valueCaps: 'S',
      modifier: false,
    },
    KeyD: {
      key: 'd',
      valueNormal: 'd',
      valueShift: 'D',
      valueShiftCaps: 'd',
      valueCaps: 'D',
      modifier: false,
    },
    KeyF: {
      key: 'f',
      valueNormal: 'f',
      valueShift: 'F',
      valueShiftCaps: 'f',
      valueCaps: 'F',
      modifier: false,
    },
    KeyG: {
      key: 'g',
      valueNormal: 'g',
      valueShift: 'G',
      valueShiftCaps: 'g',
      valueCaps: 'G',
      modifier: false,
    },
    KeyH: {
      key: 'h',
      valueNormal: 'h',
      valueShift: 'H',
      valueShiftCaps: 'h',
      valueCaps: 'H',
      modifier: false,
    },
    KeyJ: {
      key: 'j',
      valueNormal: 'j',
      valueShift: 'J',
      valueShiftCaps: 'j',
      valueCaps: 'J',
      modifier: false,
    },
    KeyK: {
      key: 'k',
      valueNormal: 'k',
      valueShift: 'K',
      valueShiftCaps: 'k',
      valueCaps: 'K',
      modifier: false,
    },
    KeyL: {
      key: 'l',
      valueNormal: 'l',
      valueShift: 'L',
      valueShiftCaps: 'l',
      valueCaps: 'L',
      modifier: false,
    },
    Semicolon: {
      key: ';',
      valueNormal: ';',
      valueShift: ':',
      valueShiftCaps: ':',
      valueCaps: ';',
      modifier: false,
    },
    Quote: {
      key: '\'',
      valueNormal: '\'',
      valueShift: '"',
      valueShiftCaps: '"',
      valueCaps: '\'',
      modifier: false,
    },
    Backslash: {
      key: '\\',
      valueNormal: '\\',
      valueShift: '|',
      valueShiftCaps: '|',
      valueCaps: '\\',
      modifier: false,
    },
    ShiftLeft: {
      key: 'shift',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    IntlBackslash: {
      key: '`',
      valueNormal: '`',
      valueShift: '~',
      valueShiftCaps: '~',
      valueCaps: '`',
      modifier: false,
    },
    KeyZ: {
      key: 'z',
      valueNormal: 'z',
      valueShift: 'Z',
      valueShiftCaps: 'z',
      valueCaps: 'Z',
      modifier: false,
    },
    KeyX: {
      key: 'x',
      valueNormal: 'x',
      valueShift: 'X',
      valueShiftCaps: 'x',
      valueCaps: 'X',
      modifier: false,
    },
    KeyC: {
      key: 'c',
      valueNormal: 'c',
      valueShift: 'C',
      valueShiftCaps: 'c',
      valueCaps: 'C',
      modifier: false,
    },
    KeyV: {
      key: 'v',
      valueNormal: 'v',
      valueShift: 'V',
      valueShiftCaps: 'v',
      valueCaps: 'V',
      modifier: false,
    },
    KeyB: {
      key: 'b',
      valueNormal: 'b',
      valueShift: 'B',
      valueShiftCaps: 'b',
      valueCaps: 'B',
      modifier: false,
    },
    KeyN: {
      key: 'n',
      valueNormal: 'n',
      valueShift: 'N',
      valueShiftCaps: 'n',
      valueCaps: 'N',
      modifier: false,
    },
    KeyM: {
      key: 'm',
      valueNormal: 'm',
      valueShift: 'M',
      valueShiftCaps: 'm',
      valueCaps: 'M',
      modifier: false,
    },
    Comma: {
      key: ',',
      valueNormal: ',',
      valueShift: '<',
      valueShiftCaps: '<',
      valueCaps: ',',
      modifier: false,
    },
    Period: {
      key: '.',
      valueNormal: '.',
      valueShift: '>',
      valueShiftCaps: '>',
      valueCaps: '.',
      modifier: false,
    },
    Slash: {
      key: '/',
      valueNormal: '/',
      valueShift: '?',
      valueShiftCaps: '?',
      valueCaps: '/',
      modifier: false,
    },
    ShiftRight: {
      key: 'shift',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    ControlLeft: {
      key: 'ctrl',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    AltLeft: {
      key: 'alt',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    MetaLeft: {
      key: 'cmd',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    Space: {
      key: ' ',
      valueNormal: ' ',
      valueShift: ' ',
      valueShiftCaps: ' ',
      valueCaps: ' ',
      modifier: false,
    },
    MetaRight: {
      key: 'cmd',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    AltRight: {
      key: 'alt',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    ArrowLeft: {
      key: '<',
      valueNormal: '<',
      valueShift: '<',
      valueShiftCaps: '<',
      valueCaps: '<',
      modifier: false,
    },
    ArrowUp: {
      key: '^',
      valueNormal: '^',
      valueShift: '^',
      valueShiftCaps: '^',
      valueCaps: '^',
      modifier: false,
    },
    ArrowRight: {
      key: '>',
      valueNormal: '>',
      valueShift: '>',
      valueShiftCaps: '>',
      valueCaps: '>',
      modifier: false,
    },
    ArrowDown: {
      key: 'v',
      valueNormal: 'v',
      valueShift: 'v',
      valueShiftCaps: 'v',
      valueCaps: 'v',
      modifier: false,
    },
  },
  ru: {
    Backquote: {
      key: '>',
      valueNormal: '>',
      valueShift: '<',
      valueShiftCaps: '<',
      valueCaps: '>',
      modifier: false,
    },
    Digit1: {
      key: '1',
      valueNormal: '1',
      valueShift: '!',
      valueShiftCaps: '!',
      valueCaps: '1',
      modifier: false,
    },
    Digit2: {
      key: '2',
      valueNormal: '2',
      valueShift: '"',
      valueShiftCaps: '"',
      valueCaps: '2',
      modifier: false,
    },
    Digit3: {
      key: '3',
      valueNormal: '3',
      valueShift: '№',
      valueShiftCaps: '№',
      valueCaps: '3',
      modifier: false,
    },
    Digit4: {
      key: '4',
      valueNormal: '4',
      valueShift: '%',
      valueShiftCaps: '%',
      valueCaps: '4',
      modifier: false,
    },
    Digit5: {
      key: '5',
      valueNormal: '5',
      valueShift: ':',
      valueShiftCaps: ':',
      valueCaps: '5',
      modifier: false,
    },
    Digit6: {
      key: '6',
      valueNormal: '6',
      valueShift: ',',
      valueShiftCaps: ',',
      valueCaps: '6',
      modifier: false,
    },
    Digit7: {
      key: '7',
      valueNormal: '7',
      valueShift: '.',
      valueShiftCaps: '.',
      valueCaps: '7',
      modifier: false,
    },
    Digit8: {
      key: '8',
      valueNormal: '8',
      valueShift: ';',
      valueShiftCaps: ';',
      valueCaps: '8',
      modifier: false,
    },
    Digit9: {
      key: '9',
      valueNormal: '9',
      valueShift: '(',
      valueShiftCaps: '(',
      valueCaps: '9',
      modifier: false,
    },
    Digit0: {
      key: '0',
      valueNormal: '0',
      valueShift: ')',
      valueShiftCaps: ')',
      valueCaps: '0',
      modifier: false,
    },
    Minus: {
      key: '-',
      valueNormal: '-',
      valueShift: '_',
      valueShiftCaps: '_',
      valueCaps: '-',
      modifier: false,
    },
    Equal: {
      key: '=',
      valueNormal: '=',
      valueShift: '+',
      valueShiftCaps: '+',
      valueCaps: '=',
      modifier: false,
    },
    Backspace: {
      key: '←',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    Tab: {
      key: 'tab',
      valueNormal: '\t',
      valueShift: '\t',
      valueShiftCaps: '\t',
      valueCaps: '\t',
      modifier: false,
    },
    KeyQ: {
      key: 'й',
      valueNormal: 'й',
      valueShift: 'Й',
      valueShiftCaps: 'й',
      valueCaps: 'Й',
      modifier: false,
    },
    KeyW: {
      key: 'ц',
      valueNormal: 'ц',
      valueShift: 'Ц',
      valueShiftCaps: 'ц',
      valueCaps: 'Ц',
      modifier: false,
    },
    KeyE: {
      key: 'у',
      valueNormal: 'у',
      valueShift: 'У',
      valueShiftCaps: 'у',
      valueCaps: 'У',
      modifier: false,
    },
    KeyR: {
      key: 'к',
      valueNormal: 'к',
      valueShift: 'К',
      valueShiftCaps: 'к',
      valueCaps: 'К',
      modifier: false,
    },
    KeyT: {
      key: 'е',
      valueNormal: 'е',
      valueShift: 'Е',
      valueShiftCaps: 'е',
      valueCaps: 'Е',
      modifier: false,
    },
    KeyY: {
      key: 'н',
      valueNormal: 'н',
      valueShift: 'Н',
      valueShiftCaps: 'н',
      valueCaps: 'Н',
      modifier: false,
    },
    KeyU: {
      key: 'г',
      valueNormal: 'г',
      valueShift: 'Г',
      valueShiftCaps: 'г',
      valueCaps: 'Г',
      modifier: false,
    },
    KeyI: {
      key: 'ш',
      valueNormal: 'ш',
      valueShift: 'Ш',
      valueShiftCaps: 'ш',
      valueCaps: 'Ш',
      modifier: false,
    },
    KeyO: {
      key: 'щ',
      valueNormal: 'щ',
      valueShift: 'Щ',
      valueShiftCaps: 'щ',
      valueCaps: 'Щ',
      modifier: false,
    },
    KeyP: {
      key: 'з',
      valueNormal: 'з',
      valueShift: 'З',
      valueShiftCaps: 'з',
      valueCaps: 'З',
      modifier: false,
    },
    BracketLeft: {
      key: 'х',
      valueNormal: 'х',
      valueShift: 'Х',
      valueShiftCaps: 'х',
      valueCaps: 'Х',
      modifier: false,
    },
    BracketRight: {
      key: 'ъ',
      valueNormal: 'ъ',
      valueShift: 'Ъ',
      valueShiftCaps: 'ъ',
      valueCaps: 'Ъ',
      modifier: false,
    },
    Enter: {
      key: 'Enter',
      valueNormal: '\n',
      valueShift: '\n',
      valueShiftCaps: '\n',
      valueCaps: '\n',
      modifier: false,
    },
    CapsLock: {
      key: 'capsLock',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    KeyA: {
      key: 'ф',
      valueNormal: 'ф',
      valueShift: 'Ф',
      valueShiftCaps: 'ф',
      valueCaps: 'Ф',
      modifier: false,
    },
    KeyS: {
      key: 'ы',
      valueNormal: 'ы',
      valueShift: 'Ы',
      valueShiftCaps: 'ы',
      valueCaps: 'Ы',
      modifier: false,
    },
    KeyD: {
      key: 'в',
      valueNormal: 'в',
      valueShift: 'В',
      valueShiftCaps: 'в',
      valueCaps: 'В',
      modifier: false,
    },
    KeyF: {
      key: 'а',
      valueNormal: 'а',
      valueShift: 'А',
      valueShiftCaps: 'а',
      valueCaps: 'А',
      modifier: false,
    },
    KeyG: {
      key: 'п',
      valueNormal: 'п',
      valueShift: 'П',
      valueShiftCaps: 'п',
      valueCaps: 'П',
      modifier: false,
    },
    KeyH: {
      key: 'р',
      valueNormal: 'р',
      valueShift: 'Р',
      valueShiftCaps: 'р',
      valueCaps: 'Р',
      modifier: false,
    },
    KeyJ: {
      key: 'о',
      valueNormal: 'о',
      valueShift: 'О',
      valueShiftCaps: 'о',
      valueCaps: 'О',
      modifier: false,
    },
    KeyK: {
      key: 'л',
      valueNormal: 'л',
      valueShift: 'Л',
      valueShiftCaps: 'л',
      valueCaps: 'Л',
      modifier: false,
    },
    KeyL: {
      key: 'д',
      valueNormal: 'д',
      valueShift: 'Д',
      valueShiftCaps: 'д',
      valueCaps: 'Д',
      modifier: false,
    },
    Semicolon: {
      key: 'ж',
      valueNormal: 'ж',
      valueShift: 'Ж',
      valueShiftCaps: 'ж',
      valueCaps: 'Ж',
      modifier: false,
    },
    Quote: {
      key: 'э',
      valueNormal: 'э',
      valueShift: 'Э',
      valueShiftCaps: 'э',
      valueCaps: 'Э',
      modifier: false,
    },
    Backslash: {
      key: 'ё',
      valueNormal: 'ё',
      valueShift: 'Ё',
      valueShiftCaps: 'ё',
      valueCaps: 'Ё',
      modifier: false,
    },
    ShiftLeft: {
      key: 'shift',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    IntlBackslash: {
      key: ']',
      valueNormal: ']',
      valueShift: '[',
      valueShiftCaps: '[',
      valueCaps: ']',
      modifier: false,
    },
    KeyZ: {
      key: 'я',
      valueNormal: 'я',
      valueShift: 'Я',
      valueShiftCaps: 'я',
      valueCaps: 'Я',
      modifier: false,
    },
    KeyX: {
      key: 'ч',
      valueNormal: 'ч',
      valueShift: 'Ч',
      valueShiftCaps: 'ч',
      valueCaps: 'Ч',
      modifier: false,
    },
    KeyC: {
      key: 'с',
      valueNormal: 'с',
      valueShift: 'С',
      valueShiftCaps: 'с',
      valueCaps: 'С',
      modifier: false,
    },
    KeyV: {
      key: 'м',
      valueNormal: 'м',
      valueShift: 'М',
      valueShiftCaps: 'м',
      valueCaps: 'М',
      modifier: false,
    },
    KeyB: {
      key: 'и',
      valueNormal: 'и',
      valueShift: 'И',
      valueShiftCaps: 'и',
      valueCaps: 'И',
      modifier: false,
    },
    KeyN: {
      key: 'т',
      valueNormal: 'т',
      valueShift: 'Т',
      valueShiftCaps: 'т',
      valueCaps: 'Т',
      modifier: false,
    },
    KeyM: {
      key: 'ь',
      valueNormal: 'ь',
      valueShift: 'Ь',
      valueShiftCaps: 'ь',
      valueCaps: 'Ь',
      modifier: false,
    },
    Comma: {
      key: 'б',
      valueNormal: 'б',
      valueShift: 'Б',
      valueShiftCaps: 'б',
      valueCaps: 'Б',
      modifier: false,
    },
    Period: {
      key: 'ю',
      valueNormal: 'ю',
      valueShift: 'Ю',
      valueShiftCaps: 'ю',
      valueCaps: 'Ю',
      modifier: false,
    },
    Slash: {
      key: '/',
      valueNormal: '/',
      valueShift: '?',
      valueShiftCaps: '?',
      valueCaps: '/',
      modifier: false,
    },
    ShiftRight: {
      key: 'shift',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    ControlLeft: {
      key: 'ctrl',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    AltLeft: {
      key: 'alt',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    MetaLeft: {
      key: 'cmd',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    Space: {
      key: ' ',
      valueNormal: ' ',
      valueShift: ' ',
      valueShiftCaps: ' ',
      valueCaps: ' ',
      modifier: false,
    },
    MetaRight: {
      key: 'cmd',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    AltRight: {
      key: 'alt',
      valueNormal: '',
      valueShift: '',
      valueShiftCaps: '',
      valueCaps: '',
      modifier: true,
    },
    ArrowLeft: {
      key: '<',
      valueNormal: '<',
      valueShift: '<',
      valueShiftCaps: '<',
      valueCaps: '<',
      modifier: false,
    },
    ArrowUp: {
      key: '^',
      valueNormal: '^',
      valueShift: '^',
      valueShiftCaps: '^',
      valueCaps: '^',
      modifier: false,
    },
    ArrowRight: {
      key: '>',
      valueNormal: '>',
      valueShift: '>',
      valueShiftCaps: '>',
      valueCaps: '>',
      modifier: false,
    },
    ArrowDown: {
      key: 'v',
      valueNormal: 'v',
      valueShift: 'v',
      valueShiftCaps: 'v',
      valueCaps: 'v',
      modifier: false,
    },
  },
};

export default keys;
